services:
  - type: web
    name: clinic-booking-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi --log-file -"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
