# Generated by Django 6.1.1 on 2026-09-20 17:58

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, validators=[booking.models.validate_eg_phone], verbose_name='الموبايل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.specialty', verbose_name='التخصص')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
